import pytest

from klin import render

from conftest import record


def test_pipes_in_a_value_are_escaped():
    # A pipe splits a table cell even inside backticks. Left unescaped it
    # silently mangles the row rather than erroring.
    assert render.escape("forge: github | forgejo | none") == (
        "forge: github \\| forgejo \\| none"
    )


def test_newlines_collapse_so_a_cell_stays_one_row():
    assert render.escape("two\nlines") == "two lines"


def test_table_has_one_row_per_record_plus_a_header():
    body = render.table([record("a"), record("b")])
    rows = body.splitlines()
    assert len(rows) == 4
    assert rows[0].startswith("| Asset |")


def test_every_rendered_row_has_the_same_cell_count():
    item = record("piped")
    item["licence"]["id"] = "Weird|Licence"
    item["notes"] = "a note with a | pipe"
    rows = render.table([item]).splitlines()
    counts = set()
    for row in rows:
        stripped = row.replace("\\|", "")
        counts.add(stripped.count("|"))
    assert len(counts) == 1


def test_details_render_notes_and_modifications(repo):
    item = record("kaykit")
    item["notes"] = "203 byte-identical copies of one atlas."
    item["modifications"] = ["Pruned fbx/ and obj/ on import."]
    body = render.details([item])
    assert "203 byte-identical copies" in body
    assert "- Pruned fbx/ and obj/ on import." in body


def test_details_skip_records_with_nothing_extra():
    assert render.details([record("plain")]) == ""


# ------------------------------------------------- what says it made a record


def test_a_generated_record_names_the_model_and_its_licence():
    """The shape klin has always written. Untested until a second one existed."""
    item = record("plate")
    item["produced_by"] = {"model_id": "civitai-725031", "model_licence": "CC-BY-4.0"}
    body = render.details([item])
    assert "- Generated by `civitai-725031` under CC-BY-4.0" in body


def test_a_generated_record_says_so_even_with_the_fields_empty():
    item = record("plate")
    item["produced_by"] = {"model_id": None, "model_licence": None}
    assert render.details([item]) == ""


def test_a_conformed_record_names_the_tool_and_the_record_it_came_from():
    item = record("counter")
    item["produced_by"] = {"tool": "blender", "version": "5.2.0"}
    item["source"]["derived_from"] = "battleroach-tavern"
    body = render.details([item])
    assert "- Conformed by `blender 5.2.0` from `battleroach-tavern`" in body


def test_a_conformed_record_drops_the_clause_when_nothing_derived_it():
    item = record("counter")
    item["produced_by"] = {"tool": "blender", "version": "5.2.0"}
    body = render.details([item])
    assert "- Conformed by `blender 5.2.0`" in body
    assert "from" not in body


def test_a_conformer_never_claims_a_model_generated_it():
    """The defect this pair of branches exists to stop.

    One shape read as the other prints `Generated by an unrecorded model under
    an unrecorded licence` into a committed licence document, which is a false
    sentence about provenance rather than a formatting slip.
    """
    item = record("counter")
    item["produced_by"] = {"tool": "blender", "version": "5.2.0"}
    body = render.details([item])
    assert "Generated by" not in body
    assert "unrecorded" not in body


def test_an_unrecognised_shape_prints_nothing_rather_than_a_guess():
    item = record("odd")
    item["produced_by"] = {"who": "somebody"}
    assert render.details([item]) == ""


def test_produced_by_as_a_string_is_a_blank_line_not_a_traceback():
    """A hand-edited ledger is a supported way to write a record."""
    item = record("odd")
    item["produced_by"] = "blender"
    assert render.details([item]) == ""


def test_splice_replaces_only_the_marked_block(repo):
    made = repo()
    text = made.licenses()
    out = render.splice(text, "records", "GENERATED")
    assert "GENERATED" in out
    assert "Hand-written policy lives here" in out
    assert "Also hand-written, also untouched" in out


def test_splice_is_idempotent(repo):
    made = repo()
    once = render.splice(made.licenses(), "records", "GENERATED")
    twice = render.splice(once, "records", "GENERATED")
    assert once == twice


def test_check_detects_a_hand_edit_inside_the_block(repo):
    made = repo()
    text = render.splice(made.licenses(), "records", "GENERATED")
    assert render.check(text, "records", "GENERATED")
    tampered = text.replace("GENERATED", "SOMEONE EDITED THIS")
    assert not render.check(tampered, "records", "GENERATED")


def test_missing_markers_explain_how_to_add_them():
    with pytest.raises(render.RenderError) as caught:
        render.splice("# doc\n\nno markers here\n", "records", "X")
    message = str(caught.value)
    assert "<!-- klin:begin records -->" in message
    assert "<!-- klin:end records -->" in message


def test_markers_in_the_wrong_order_are_rejected():
    text = "<!-- klin:end records -->\n<!-- klin:begin records -->\n"
    with pytest.raises(render.RenderError):
        render.splice(text, "records", "X")


def test_an_empty_ledger_renders_a_statement_not_a_blank(repo):
    assert "No assets recorded yet" in render.body([])
