"""Render ledger records into a marked block inside a prose policy document.

The policy document is hand-written and stays that way. Only the block between
the markers is generated, and `check()` exists so that a hand-edit inside the
block is caught by a gate rather than discovered a year later.

Deliberately a compact table plus short per-record detail, not a full rendering
of everything a human wrote. Narrative belongs in the prose around the block; a
schema would flatten it.
"""

import re

from . import ledger

BEGIN = "<!-- klin:begin %s -->"
END = "<!-- klin:end %s -->"


class RenderError(Exception):
    pass


def escape(value):
    """Make a value safe inside a markdown table cell.

    Pipes split cells even inside backticks, which silently mangles the row, so
    they are escaped rather than trusted.
    """
    if value is None:
        return ""
    text = " ".join(str(value).split())
    return text.replace("|", "\\|")


def _link(url, label=None):
    if ledger.is_empty(url):
        return ""
    return "[%s](%s)" % (escape(label or url), url)


def _attribution(record):
    required = ledger.field(record, "licence.attribution_required")
    if required is None:
        return "unrecorded"
    return "**required**" if required else "not required"


def table(records):
    rows = [
        "| Asset | Licence | Attribution | Retrieved | Source |",
        "|---|---|---|---|---|",
    ]
    for record in sorted(records, key=lambda r: r["id"]):
        paths = ", ".join("`%s`" % escape(p) for p in record.get("paths") or [])
        asset = "`%s`" % escape(record["id"])
        if record.get("kind"):
            asset += " (%s)" % escape(record["kind"])
        if paths:
            asset += "<br>%s" % paths
        rows.append(
            "| %s | %s | %s | %s | %s |"
            % (
                asset,
                escape(ledger.field(record, "licence.id") or "unrecorded"),
                _attribution(record),
                escape(ledger.field(record, "source.retrieved")),
                _link(ledger.field(record, "source.url")),
            )
        )
    return "\n".join(rows)


def produced_sentence(produced, record):
    """How a record says what made it, for the two things that can make one.

    A generator and a conformer both fill `produced_by`, and they are not the
    same claim. A model produced pixels that did not exist before, and the
    sentence that matters is which model under which licence. A conformer
    transformed a file that already existed, and the sentence that matters is
    which tool and from which record, because the licence is the source's and
    is already printed in the table above.

    Told apart by shape rather than by a discriminator field, because the
    generator shape is already written into a committed ledger and adding a
    field to it now would mean migrating records to keep a sentence rendering.
    An unrecognised shape prints nothing: this writes into a licence document,
    and a plausible sentence about provenance nobody recorded is worse there
    than a missing one.
    """
    if not isinstance(produced, dict):
        return ""
    if produced.get("model_id") or produced.get("model_licence"):
        return "- Generated by `%s` under %s" % (
            escape(produced.get("model_id") or "an unrecorded model"),
            escape(produced.get("model_licence") or "an unrecorded licence"),
        )
    if produced.get("tool"):
        tool = produced["tool"]
        if produced.get("version"):
            tool = "%s %s" % (tool, produced["version"])
        source = ledger.field(record, "source.derived_from")
        if source:
            return "- Conformed by `%s` from `%s`" % (escape(tool), escape(source))
        return "- Conformed by `%s`" % escape(tool)
    return ""


def details(records):
    chunks = []
    for record in sorted(records, key=lambda r: r["id"]):
        notes = record.get("notes")
        mods = record.get("modifications") or []
        produced = record.get("produced_by") or {}
        # Resolved before the skip test rather than after, so a shape this does
        # not recognise leaves the record out entirely instead of emitting a
        # heading with nothing under it.
        sentence = produced_sentence(produced, record) if produced else ""
        if ledger.is_empty(notes) and not mods and not sentence:
            continue
        lines = ["**`%s`**" % escape(record["id"])]
        if not ledger.is_empty(notes):
            lines.append("")
            lines.append(escape(notes).replace("\\|", "|"))
        if sentence:
            lines.append("")
            lines.append(sentence)
        if mods:
            lines.append("")
            for mod in mods:
                lines.append("- %s" % escape(mod).replace("\\|", "|"))
        chunks.append("\n".join(lines))
    return "\n\n".join(chunks)


def body(records):
    """The full generated block, markers excluded."""
    if not records:
        return "*No assets recorded yet.*"
    parts = [table(records)]
    extra = details(records)
    if extra:
        parts.append(extra)
    return "\n\n".join(parts)


def _markers(text, name):
    begin, end = BEGIN % name, END % name
    start = text.find(begin)
    stop = text.find(end)
    if start < 0 or stop < 0:
        raise RenderError(
            "markers for %r not found; add these two lines to the document:\n%s\n%s"
            % (name, begin, end)
        )
    if stop < start:
        raise RenderError("markers for %r are in the wrong order" % name)
    return begin, end, start, stop


def splice(text, name, block):
    """Return `text` with the marked block replaced by `block`."""
    begin, end, start, stop = _markers(text, name)
    head = text[:start]
    tail = text[stop + len(end):]
    return "%s%s\n\n%s\n\n%s%s" % (head, begin, block.strip("\n"), end, tail)


def check(text, name, block):
    """True when the document already holds exactly this block."""
    return splice(text, name, block) == text


def current(text, name):
    """The block as it currently sits in the document, markers excluded."""
    begin, end, start, stop = _markers(text, name)
    return text[start + len(begin):stop].strip("\n")


_TRAILING = re.compile(r"[ \t]+$", re.M)


def normalise(text):
    return _TRAILING.sub("", text)
